# Generated by Django 4.2.25 on 2025-10-12 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collab',
            fields=[
                ('idcollab', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'collab',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Created',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trending', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'created',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('idplaylist', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'playlist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('idsong', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('link', models.CharField(max_length=150)),
                ('artist', models.CharField(blank=True, max_length=45, null=True)),
                ('imagelink', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('spotify_id', models.CharField(max_length=50, unique=True)),
                ('duration_string', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'song',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=9)),
                ('idauth', models.OneToOneField(db_column='idauth', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requestfriendship',
            fields=[
                ('idrf', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('iduserrecieve', models.ForeignKey(db_column='iduserrecieve', on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to='app.user')),
                ('idusersend', models.ForeignKey(db_column='idusersend', on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to='app.user')),
            ],
            options={
                'db_table': 'requestfriendship',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requestcollab',
            fields=[
                ('idrc', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('idcollab', models.ForeignKey(db_column='idcollab', on_delete=django.db.models.deletion.CASCADE, to='app.collab')),
                ('iduserrecieve', models.ForeignKey(db_column='iduserrecieve', on_delete=django.db.models.deletion.CASCADE, related_name='requestcollab_received', to='app.user')),
                ('idusersend', models.ForeignKey(db_column='idusersend', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'requestcollab',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.created')),
                ('iduser', models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'rated',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('idpur', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('iduser', models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'purchased',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Participated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idcollab', models.ForeignKey(db_column='idcollab', on_delete=django.db.models.deletion.CASCADE, to='app.collab')),
                ('iduser', models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'participated',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.created')),
                ('iduser', models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'liked',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.requestfriendship')),
            ],
            options={
                'db_table': 'friendship',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='created',
            name='idplaylist',
            field=models.ForeignKey(db_column='idplaylist', on_delete=django.db.models.deletion.CASCADE, to='app.playlist'),
        ),
        migrations.AddField(
            model_name='created',
            name='iduser',
            field=models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idplaylist', models.ForeignKey(db_column='idplaylist', on_delete=django.db.models.deletion.CASCADE, to='app.playlist')),
                ('idsong', models.ForeignKey(db_column='idsong', on_delete=django.db.models.deletion.CASCADE, to='app.song')),
                ('iduser', models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'contains',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='collab',
            name='idplaylist',
            field=models.ForeignKey(blank=True, db_column='idplaylist', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.playlist'),
        ),
        migrations.AddField(
            model_name='collab',
            name='iduser',
            field=models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AddConstraint(
            model_name='requestfriendship',
            constraint=models.UniqueConstraint(fields=('idusersend', 'iduserrecieve'), name='unique_friend_request'),
        ),
        migrations.AddConstraint(
            model_name='rated',
            constraint=models.UniqueConstraint(fields=('created', 'iduser'), name='unique_rated'),
        ),
        migrations.AddConstraint(
            model_name='liked',
            constraint=models.UniqueConstraint(fields=('created', 'iduser'), name='unique_liked'),
        ),
        migrations.AddConstraint(
            model_name='created',
            constraint=models.UniqueConstraint(fields=('iduser', 'idplaylist'), name='unique_created'),
        ),
        migrations.AddConstraint(
            model_name='contains',
            constraint=models.UniqueConstraint(fields=('idplaylist', 'idsong'), name='unique_playlist_song'),
        ),
    ]
