# Generated by Django 5.2.6 on 2025-10-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collab',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contains',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='created',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='friendship',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='liked',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='participated',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='purchased',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rated',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='requestcollab',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='requestfriendship',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
